# Generated by Django 3.2.5 on 2021-09-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sexe',
            field=models.CharField(blank=True, choices=[('F', 'FEMININ'), ('M', 'MASCULIN')], default='M', max_length=10, null=True),
        ),
    ]
