# Generated by Django 3.2.5 on 2021-09-01 09:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriePs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categorie Professionel de Santé',
                'verbose_name_plural': 'Categories Professionel de Santé',
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Departement',
                'verbose_name_plural': 'Departements',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Localité',
                'verbose_name_plural': 'Localités',
            },
        ),
        migrations.CreateModel(
            name='QualitePs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Qualite Professionel de Santé',
                'verbose_name_plural': 'Qualites Professionel de Santé',
            },
        ),
        migrations.CreateModel(
            name='Secteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Secteur  Structure de Santé',
                'verbose_name_plural': 'Secteur  Structure de Santé',
            },
        ),
        migrations.CreateModel(
            name='SpecialitePs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Specialite Professionel de Santé',
                'verbose_name_plural': 'Specialites Professionel de Santé',
            },
        ),
        migrations.CreateModel(
            name='StatutJuridique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statut Juridique',
                'verbose_name_plural': 'Statut Juridiques',
            },
        ),
        migrations.CreateModel(
            name='TypeStructureSante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Type  Structure de Santé',
                'verbose_name_plural': 'Type  Structure de Santé',
            },
        ),
        migrations.CreateModel(
            name='StructureSante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('adresse_geo', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(max_length=50)),
                ('telephone2', models.CharField(blank=True, max_length=50, null=True)),
                ('telephone3', models.CharField(blank=True, max_length=50, null=True)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('code_four', models.CharField(blank=True, max_length=50, null=True)),
                ('localisation_gps', models.CharField(blank=True, max_length=50, null=True)),
                ('name_responsable', models.CharField(max_length=255, verbose_name='Nom du responsable')),
                ('email_responsable', models.EmailField(blank=True, max_length=255, null=True)),
                ('tel_reponsable', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('logo', models.ImageField(blank=True, max_length=300, null=True, upload_to='static/MEDIA', verbose_name='Logo ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Infos. complémentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('numImmatriculation', models.CharField(max_length=255)),
                ('enAccorPrealable', models.BooleanField(default=False)),
                ('localite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.localite', verbose_name='localite')),
                ('secteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.secteur')),
                ('statutJuridique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.statutjuridique', verbose_name='Statut Juridique')),
                ('structureParent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structureEnfant', to='structure.structuresante')),
                ('typestructureSante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.typestructuresante')),
            ],
            options={
                'verbose_name': 'Structure de Stanté',
                'verbose_name_plural': 'Structures de Stanté',
            },
        ),
        migrations.CreateModel(
            name='SousPrefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.departement')),
            ],
            options={
                'verbose_name': 'Sous-Prefecture',
                'verbose_name_plural': 'Sous-Prefectures',
            },
        ),
        migrations.AddField(
            model_name='secteur',
            name='typeStructureSante',
            field=models.ManyToManyField(to='structure.TypeStructureSante'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.district')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='ProfessionelSante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, max_length=255, null=True)),
                ('numOrdre', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('StructureSante', models.ManyToManyField(to='structure.StructureSante')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.categorieps')),
                ('qualite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.qualiteps')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.specialiteps')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professionel de Santé',
                'verbose_name_plural': 'Professionels de Santé',
            },
        ),
        migrations.AddField(
            model_name='localite',
            name='sousPrefecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.sousprefecture'),
        ),
        migrations.AddField(
            model_name='departement',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.region'),
        ),
        migrations.CreateModel(
            name='AgentStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroAgent', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('structureSante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.structuresante')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent des Structure de Stanté',
                'verbose_name_plural': 'Agents desStructures de Stanté',
            },
        ),
    ]
